language: ruby
rvm:
  - "1.9.3"
before_install: 
  - git clone  https://github.com/melezhik/cookbooks.git
  - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  - sudo cpanm CPAN
script: PATH=$PATH:$PWD/lib/bin  GEM_PATH=$GEM_PATH:$PWD/lib sudo cucumber












