language: ruby
rvm:
  - "1.9.3"
before_install: 
  - git clone  https://github.com/melezhik/cookbooks.git
  - gem install chef --no-ri --no-rdoc
  - gem install cucumber-nagios --no-ri --no-rdoc
  - rvmsudo_secure_path=1 rvmsudo chef-solo -c solo.rb -o cpan::bootstrap 
script: rvmsudo_secure_path=1 rvmsudo cucumber 
